calibration:
  frame_convention: pose7=[x,y,z,qx,qy,qz,qw], meters, xyzw quaternion
  controller_to_gripper_tcp:
    left:
      position:
      - 0.12068467
      - 0.02142489
      - -0.21669616
      quaternion:
      - -0.1464
      - 0.3536
      - -0.3536
      - 0.8536
    right:
      position:
      - 0.12068467
      - -0.02142489
      - -0.21669616
      quaternion:
      - 0.1464
      - 0.3536
      - 0.3536
      - 0.8536
