"""Piper IK solver: robot spec and collision model.

The only robot-specific concerns here are:

1. ``_build_robot_collision`` — restricts pyroki's collision pairs to
   cross-arm and opposite-base-arm contacts for Piper's dual-arm geometry.
2. ``PIPER_KINEMATICS_SPEC`` — the single source of truth mapping Piper's
   logical joints to URDF link/joint names.

``KinematicsSolver`` is generated by :func:`~dexumi.robots.kinematics.make_kinematics_solver`
and is equivalent to ``BimanualPyrokiSolver`` bound to the Piper spec.
All IK logic lives in :mod:`dexumi.robots.kinematics`.
"""

from __future__ import annotations

import logging

import jax.numpy as jnp
import numpy as np
import pyroki as pk
import yourdfpy

from dexumi.robots.kinematics import KinematicsConfig, RobotKinematicsSpec, make_kinematics_solver

from .shared import (
    URDF_PATH,
    Joint,
    urdf_arm_joint_names,
    urdf_body_name,
    urdf_revolute_joint_names,
)

_logger = logging.getLogger(__name__)


def _build_robot_collision(
    urdf: yourdfpy.URDF,
    robot: pk.Robot,
    config: KinematicsConfig,
) -> pk.collision.RobotCollision:
    """Build a Piper collision model restricted to meaningful safety pairs."""
    link_names = [link.name for link in urdf.robot.links]

    def is_left_arm(name: str) -> bool:
        return name.startswith("left_link")

    def is_right_arm(name: str) -> bool:
        return name.startswith("right_link")

    def is_left_base(name: str) -> bool:
        return name == "left_base_link"

    def is_right_base(name: str) -> bool:
        return name == "right_base_link"

    def keep_pair(a: str, b: str) -> bool:
        cross_arm = (is_left_arm(a) and is_right_arm(b)) or (
            is_right_arm(a) and is_left_arm(b)
        )
        opposite_base_arm = (
            (is_left_base(a) and is_right_arm(b))
            or (is_left_base(b) and is_right_arm(a))
            or (is_right_base(a) and is_left_arm(b))
            or (is_right_base(b) and is_left_arm(a))
        )
        return cross_arm or opposite_base_arm

    ignore: set[tuple[str, str]] = set()
    for i, a in enumerate(link_names):
        for b in link_names[i + 1 :]:
            if not keep_pair(a, b):
                ignore.add((a, b))

    rc = pk.collision.RobotCollision.from_urdf(urdf, user_ignore_pairs=tuple(ignore))
    q0 = jnp.zeros(robot.joints.num_actuated_joints)
    distances = np.asarray(rc.compute_self_collision_distance(robot, q0))
    active_i = np.asarray(rc.active_idx_i)
    active_j = np.asarray(rc.active_idx_j)
    for index in np.where(distances < config.self_collision_margin)[0]:
        ignore.add((rc.link_names[active_i[index]], rc.link_names[active_j[index]]))

    rc = pk.collision.RobotCollision.from_urdf(urdf, user_ignore_pairs=tuple(ignore))
    _logger.info("RobotCollision: restricted to %d Piper safety pairs.", len(rc.active_idx_i))
    return rc


PIPER_KINEMATICS_SPEC = RobotKinematicsSpec(
    name="Piper",
    urdf_path=URDF_PATH,
    left_ee_link=urdf_body_name(Joint.JOINT_6, is_left=True),
    right_ee_link=urdf_body_name(Joint.JOINT_6, is_left=False),
    left_shoulder_link=urdf_body_name(Joint.JOINT_1, is_left=True),
    right_shoulder_link=urdf_body_name(Joint.JOINT_1, is_left=False),
    left_arm_joint_names=tuple(urdf_revolute_joint_names(is_left=True)),
    right_arm_joint_names=tuple(urdf_revolute_joint_names(is_left=False)),
    left_control_joint_names=tuple(urdf_arm_joint_names(is_left=True)),
    right_control_joint_names=tuple(urdf_arm_joint_names(is_left=False)),
    left_elbow_link=urdf_body_name(Joint.JOINT_3, is_left=True),
    right_elbow_link=urdf_body_name(Joint.JOINT_3, is_left=False),
    collision_builder=_build_robot_collision,
)

KinematicsSolver = make_kinematics_solver(PIPER_KINEMATICS_SPEC)
