"""Axol IK solver: robot spec and collision model.

The only robot-specific concerns here are:

1. ``_build_robot_collision`` — restricts pyroki's collision pairs to
   torso-vs-arm contacts, which are the only pairs that matter for Axol.
2. ``AXOL_KINEMATICS_SPEC`` — the single source of truth mapping Axol's
   logical joints to URDF link/joint names.

``KinematicsSolver`` is generated by :func:`~dexumi.robots.kinematics.make_kinematics_solver`
and is equivalent to ``BimanualPyrokiSolver`` bound to the Axol spec.
All IK logic lives in :mod:`dexumi.robots.kinematics`.
"""

from __future__ import annotations

import logging

import jax.numpy as jnp
import numpy as np
import pyroki as pk
import yourdfpy

from dexumi.robots.kinematics import KinematicsConfig, RobotKinematicsSpec, make_kinematics_solver

from .shared import URDF_PATH, Joint, urdf_arm_joint_names, urdf_body_name

_logger = logging.getLogger(__name__)

_TORSO_LINKS: tuple[str, ...] = ("base", "s1")


def _build_robot_collision(
    urdf: yourdfpy.URDF,
    robot: pk.Robot,
    config: KinematicsConfig,
) -> pk.collision.RobotCollision:
    """Build Axol self-collision restricted to torso-arm pairs."""
    link_names = [link.name for link in urdf.robot.links]

    def is_arm(name: str) -> bool:
        return name.startswith("left_") or name.startswith("right_")

    def is_torso(name: str) -> bool:
        return name in _TORSO_LINKS

    ignore: set[tuple[str, str]] = set()
    for i, a in enumerate(link_names):
        for b in link_names[i + 1 :]:
            if not ((is_torso(a) and is_arm(b)) or (is_torso(b) and is_arm(a))):
                ignore.add((a, b))

    rc = pk.collision.RobotCollision.from_urdf(urdf, user_ignore_pairs=tuple(ignore))
    q0 = jnp.zeros(robot.joints.num_actuated_joints)
    distances = np.asarray(rc.compute_self_collision_distance(robot, q0))
    active_i = np.asarray(rc.active_idx_i)
    active_j = np.asarray(rc.active_idx_j)
    for index in np.where(distances < config.self_collision_margin)[0]:
        ignore.add((rc.link_names[active_i[index]], rc.link_names[active_j[index]]))

    rc = pk.collision.RobotCollision.from_urdf(urdf, user_ignore_pairs=tuple(ignore))
    _logger.info("RobotCollision: restricted to %d Axol torso-arm pairs.", len(rc.active_idx_i))
    return rc


AXOL_KINEMATICS_SPEC = RobotKinematicsSpec(
    name="Axol",
    urdf_path=URDF_PATH,
    left_ee_link=urdf_body_name(Joint.GRIPPER, is_left=True),
    right_ee_link=urdf_body_name(Joint.GRIPPER, is_left=False),
    left_shoulder_link=urdf_body_name(Joint.SHOULDER_1, is_left=True),
    right_shoulder_link=urdf_body_name(Joint.SHOULDER_1, is_left=False),
    left_arm_joint_names=tuple(urdf_arm_joint_names(is_left=True)),
    right_arm_joint_names=tuple(urdf_arm_joint_names(is_left=False)),
    left_elbow_link=urdf_body_name(Joint.ELBOW, is_left=True),
    right_elbow_link=urdf_body_name(Joint.ELBOW, is_left=False),
    collision_builder=_build_robot_collision,
)

KinematicsSolver = make_kinematics_solver(AXOL_KINEMATICS_SPEC)
